---
title: "Data Quality Check"
author: "Valerii Chirkov"
date: "August 5, 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
# Load packages and setup paths

library("pacman")
p_load(tidyverse, kableExtra, chron, modelsummary)

source('preprocessing.R')

data_path = Sys.getenv("Main1_data_path")
jatos_data_path = paste0(data_path, "jatos_results_20220805083335.txt")
jatos_meta_path = paste0(data_path, "jatos_meta_20220805083346.csv")
prolific_meta_path = paste0(data_path, "prolific_export_62e791cf7c1a911514599f70 (1).csv")

```


```{r}
# Read data from jatos

data_full <- read_results(jatos_data_path)
data_full <- bind_rows(data_full) %>% 
  mutate(subj = substring(ppid, 0, 10),
         # prolific_id = substring(`pre_questionnaire_3_prolific_id _begin_quest`, 0, 10),
         prolific_id = `pre_questionnaire_3_prolific_id _begin_quest`,
         block_num = recode_factor(
           as.factor(block_num), `2` = "Main Block 1", `4` = "Main Block 2",
           `1` = "Practice 1", `3` = "Practice 2"))

data_meta <- read.csv(file = jatos_meta_path, stringsAsFactors = F)
prolific_meta <- read.csv(file = prolific_meta_path, stringsAsFactors = F)

data_meta['prolific_id'] = ''
data_meta['Age'] = ''
data_meta['Sex'] = ''
data_meta['uxf_id'] = ''
n = 1
for (s in unique(data_full$subj)) {
  data_meta$uxf_id[n] = s
  n = n + 1}

n = 1
for (s in unique(data_full$prolific_id)) {
  data_meta$prolific_id[n] = s
  data_meta$Age[n] = prolific_meta$Age[prolific_meta$Participant.id == s]
  data_meta$Sex[n] = prolific_meta$Sex[prolific_meta$Participant.id == s]
  n = n + 1
  
  }


subj_correct <- data_full %>%
  mutate(is_correct = ifelse(
    (subject_response < 0 & coherence < 0) | 
      (subject_response > 0 & coherence > 0), 1, 0),
     block_num = recode_factor(
           as.factor(block_num),
           `Main Block 1` = "Catch", 
           `Main Block 2` = "Catch",
           `Practice 1` = "Practice 1",
           `Practice 2` = "Practice 2")) %>%
  group_by(subj, block_num) %>% 
  summarise(
    n_correct = sum(is_correct, na.rm = T),
  ) %>% 
  pivot_wider(names_from = block_num, values_from = n_correct) %>% 
  mutate(Catch = Catch / 32, 
         `Practice 1` = `Practice 1` / 10,
         `Practice 2` = `Practice 2` / 10) %>% 
  ungroup() %>% 
  arrange(subj)

```

```{r}

subj_means <- data_full %>%
  filter(is_catch != "True", is_practice != "True") %>%
  group_by(subj) %>%
  summarise(
    median_rt = median(subject_response_time),
    mean_rt = mean(subject_response_time),
    sd_rt = sd(subject_response_time),
    mean_alignment = mean(subject_follows_group_decision),
    sd_alignment = sd(subject_follows_group_decision),
    task_time = mean(task_presentation_time),
    congruency_order = unique(congruency_order),
    left_hand_color = unique(subject_left_flag_color),
    task_difficulty = unique(`post_questionnaire_1 _end_quest`),
    instruction_difficulty = unique(`post_questionnaire_2 _end_quest`),
    browser = unique(`post_questionnaire_7 _end_quest`),
    comment = unique(`post_questionnaire_10 _end_quest`)
  ) %>%
  ungroup() %>% 
  arrange(subj)

subj_breaks <- data_full %>%
  filter(trial_num == 74) %>% # practice + main block
  mutate(break_len = (end_time - start_time) / 60) %>% 
  arrange(subj)

subj_max_pause <- data_full %>%
  mutate(time_diff = end_time - start_time) %>%
  group_by(subj) %>%
  summarise(
      max_pause = max(time_diff) / 60
  ) %>% 
  arrange(subj)


data_meta <- data_meta %>%
  arrange(uxf_id) %>%  
  mutate(
    catch = subj_correct$Catch,
    practice_1 = subj_correct$`Practice 1`,
    practice_2 = subj_correct$`Practice 2`,
    `m_rt_(s)` = subj_means$mean_rt, # subj_means$median_rt,
    sd_rt = subj_means$sd_rt,
    alignment = subj_means$mean_alignment,
    `task_time_(s)` = subj_means$task_time,
    `duration_(m)` = minutes(strptime(Duration, format = "%H:%M:%S")) + 
      hours(strptime(Duration, format = "%H:%M:%S")) * 60,
    congruency_order = ifelse(subj_means$congruency_order=="incongruentFirst", -1, 1),
    `max_pause_(m)` = subj_max_pause$max_pause, # in minutes
    `break_len_(m)` = subj_breaks$break_len,
    left_hand_color = subj_means$left_hand_color,
    browser = subj_means$browser,
    age = as.numeric(Age),
    sex = as.factor(Sex),
    valid_data = ((catch > 0.6) & 
                  (catch > mean(catch) - sd(catch) * 3) & 
                  (`m_rt_(s)` < mean(`m_rt_(s)`) + mean(sd_rt) * 3))
    ) %>% 
  select(
    "prolific_id", "uxf_id", "Start.Time", "duration_(m)", "max_pause_(m)", "break_len_(m)", 
    "practice_1", "practice_2", "catch", "m_rt_(s)", "sd_rt", 
    "alignment", "task_time_(s)", "congruency_order", "left_hand_color", "browser", "age", "sex",
    "valid_data")
```

# Sample overview

```{r}
good_col = "#9C964A" 
warn_col = "#85D4E3"
crit_col = "#972D15" # "#F4B5BD"
inval_col = "#FAD77B"

data_meta_table <- data_meta %>% 
  mutate_if(is.numeric, round, digits = 3) %>% 
  mutate(
    `duration_(m)` = cell_spec(
      `duration_(m)`, 
      color = ifelse((`duration_(m)`) > 35 | (`duration_(m)` < 15), warn_col, good_col)), # duration
    `max_pause_(m)` = cell_spec(
      `max_pause_(m)`,
      color = ifelse(`max_pause_(m)` > 5, warn_col, good_col)), # max_pause > 5 min
    `break_len_(m)` = cell_spec(
      `break_len_(m)`,
      color = ifelse(`break_len_(m)` > 5, warn_col, good_col)), # max_pause > 5 min
    catch = cell_spec(
      catch, 
      color = ifelse((catch) < 0.6 | (catch < mean(catch) - sd(catch) * 3), crit_col, good_col)), # catch
    practice_1 = cell_spec(
      practice_1, 
      color = ifelse(practice_1 < 0.6, warn_col, good_col)), # practice
    practice_2 = cell_spec(
      practice_2, 
      color = ifelse(practice_2 < 0.6, warn_col, good_col)), # practice
    `m_rt_(s)` = cell_spec(
      `m_rt_(s)`, 
      color = ifelse(`m_rt_(s)` > mean(`m_rt_(s)`) + mean(sd_rt) * 3, crit_col, good_col)), # rt
    `task_time_(s)` = cell_spec(
      `task_time_(s)`, 
      color = ifelse(mean(abs(`task_time_(s)` - 3.07)) > 0.02, crit_col, good_col)),
    browser = cell_spec(
      browser, 
      color = ifelse((browser == "Chrome") | (browser == "Firefox"), good_col, warn_col)),
  ) %>%
  rename(`mean_rt_(s)` = `m_rt_(s)`) %>%
  select(-sd_rt) %>%
  arrange(desc(`Start.Time`)) %>%
  mutate(n = rev(seq(1:n())))
  
data_meta_table %>% 
  select(-c(valid_data, prolific_id, `Start.Time`, `task_time_(s)`, browser)) %>% 
  rename(id = uxf_id, acc_catch = catch, alignment_rate = alignment,
         `break_between_blocks_(m)` = `break_len_(m)`,
         `max_break_(m)` = `max_pause_(m)`) %>%
  mutate(
    congruency_order = recode_factor(
      as.factor(congruency_order), `-1` = "IC block first", `1` = "C block first"),
    left_hand_color = recode_factor(
      as.factor(left_hand_color), `-1` = "orange", `1` = "blue"),
  ) %>% 
  kbl(format = "html", escape = F, align = "c") %>%
  # column_spec(column = 3, width_min = "3.5cm") %>%  # Start.Time
  # column_spec(column = 2, width_min = "2.2cm") %>%  # uxf_id
  column_spec(column = 1, width_min = "2.2cm") %>%  # uxf_id
  row_spec(which(data_meta_table$valid_data == F), background = inval_col) %>%
  kable_styling(fixed_thead = T) %>% 
  kable_paper("hover", full_width = F, position = "center")


```


```{r}
# save meta data

meta_data <- data_meta_table %>% 
  select(-c(prolific_id, `Start.Time`, `task_time_(s)`)) %>% 
  rename(id = uxf_id, acc_catch = catch, alignment_rate = alignment,
         `break_between_blocks_(m)` = `break_len_(m)`,
         `max_break_(m)` = `max_pause_(m)`) %>%
  mutate(
    congruency_order = recode_factor(
      as.factor(congruency_order), `-1` = "IC block first", `1` = "C block first"),
    left_hand_color = recode_factor(
      as.factor(left_hand_color), `-1` = "orange", `1` = "blue"),
  )

saveRDS(meta_data, file = paste0(data_path, "meta_data.rds"))
saveRDS(meta_data, file = paste0("data/", "meta_data.rds"))
write.csv(meta_data,  paste0("data/", "meta_data.csv"), row.names = FALSE)
```

```{r}
data_full$valid_subject = F
data_full$age = 0

for (s in unique(data_full$subj)) {
  data_full$valid_subject[data_full$subj == s] = data_meta_table$valid_data[data_meta_table$uxf_id == s]
  # data_full$age[data_full$subj == s] = data_meta$age[data_meta$subj == s]
  # data_full$sex[data_full$subj == s] = data_meta$sex[data_meta$subj == s]
}

# save data
data <- data_full %>%
  # filter(is_catch != "True", is_practice != "True") %>%
  mutate(
    block = block_num,
    congruency = recode_factor(as.factor(congruency), `-1` = "IC", `1` = "C"),
    congruency = fct_relevel(congruency, c('C', 'IC')),
    id = as.factor(subj),
    group_alignment = recode_factor(as.factor(subject_follows_group_decision), `1` = "F", `0` = "NF"),
    group_alignment = fct_relevel(group_alignment, c('NF', 'F')),
    first_agent_rt = dplyr::select(., starts_with("Agent")) %>% reduce(pmin, na.rm = T),
    first_agent_rt = first_agent_rt * 1000, # in ms
    rt = subject_response_time * 1000,  # in ms
    trial_length = end_time - start_time,
    is_catch = ifelse(is_catch == "True", T, F),
    is_practice = ifelse(is_practice == "True", T, F),
    valid_trial = rt > 500 & !is_catch & !is_practice # first condition
    
  ) %>% 
  dplyr::select(
    id, block, is_catch, is_practice, trial_num, trial_length, n_agents,
    congruency, rt, group_alignment, first_agent_rt,
    percentage_of_orange_pixels, valid_subject, valid_trial)


for (s in unique(data$id)) {
  cond = data$id == s & !data$is_catch & !data$is_practice
  data$valid_trial[cond] = 
    data$valid_trial[cond] & 
    data$rt[cond] < mean(data$rt[cond]) + sd(data$rt[cond]) * 3
  # print(mean(data$rt[cond]) + sd(data$rt[cond]) * 3)
}


contrasts(data$congruency) <- c(-0.5, +0.5) # NB!!

saveRDS(data, file = paste0(data_path, "data.rds"))
saveRDS(data, file = paste0("data/", "data.rds"))
write.csv(data,  paste0("data/", "data.csv"), row.names = FALSE)
# data <- readRDS(file = paste0(data_path, "data.rds"))
```


# Data summary

```{r}
data_meta %>%
  rename(id = uxf_id, acc_catch = catch, alignment_rate = alignment,
         `break_between_blocks_(m)` = `break_len_(m)`,`mean_rt_(s)` = `m_rt_(s)`,
         `max_break_(m)` = `max_pause_(m)`) %>% 
  datasummary_skim(fmt = "%.2f")
```

```{r}
data_meta %>%
  mutate(
    congruency_order = recode_factor(
      as.factor(congruency_order), `-1` = "incongruent block fisrt", `1` = "congruent block first"),
  ) %>% 
  group_by(congruency_order) %>% 
  summarize(n = n()) %>%
  rename(`Congruency blocks order` = congruency_order) %>% 
  kbl(format = "html", escape = F) %>%
  kable_styling(fixed_thead = T) %>% 
  kable_paper(full_width = F)
```

```{r}
data_meta %>% 
  mutate(
    left_hand_color = recode_factor(
      as.factor(left_hand_color), `-1` = "orange", `1` = "blue"),
  ) %>% 
  group_by(left_hand_color) %>%
  summarize(n = n()) %>%
  rename(`Color of the flag in participants left hand` = left_hand_color) %>% 
  kbl(format = "html", escape = F) %>%
  kable_styling(fixed_thead = T) %>% 
  kable_paper(full_width = F)
```

```{r}
data_meta %>% 
  group_by(sex) %>% 
  summarize(n = n()) %>% 
  kbl(format = "html", escape = F) %>%
  kable_styling(fixed_thead = T) %>% 
  kable_paper(full_width = F)
```


# Feedback

```{r  eval=FALSE, include=FALSE}

subj_means %>%
  select(subj, task_difficulty, instruction_difficulty) %>% 
  pivot_longer(!subj, names_to = "question", values_to = "response") %>% 
  ggplot(aes(question, response)) +
  geom_boxplot() +
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  labs(title = "Answers to the questionnaire at the end") +
  theme_minimal()

```


```{r}
subj_means %>% 
  filter(!is.na(comment)) %>% 
  select(subj, comment) %>%
  kbl(format = "html", escape = F, align = "c") %>%
  column_spec(column = 1, width_min = "2.2cm") %>%
  column_spec(column = 2, width_min = "10cm") %>%
  kable_styling(fixed_thead = T) %>% 
  kable_paper("hover", full_width = F, position = "center")

```



```{r  eval=FALSE, include=FALSE}
# The number of repetitions per condition
data_full %>%
  filter(is_catch != "True") %>% 
  group_by(n_agents, block_num) %>% 
  summarise(n = n() / nrow(data_meta)) %>%
  ggplot(aes(n_agents, block_num, fill = n)) +
  geom_tile() +
  labs(title = "The number of repetitions for main blocks and practice",
       fill = "N repeat") +
  theme_bw()

```


```{r  eval=FALSE, include=FALSE}

data_full %>%
  filter(is_catch == "True") %>% 
  group_by(n_agents, block_num) %>% 
  summarise(n = n() / nrow(data_meta)) %>%
  ggplot(aes(n_agents, block_num, fill = n)) +
  geom_tile() +
  labs(title = "The number of repetitions for catch",
       fill = "N repeat") +
  theme_bw()

```


```{r eval=FALSE, include=FALSE}
# The number of wrong responses made by agents
data_full %>% 
  filter(is_catch == "True", group_correctness == 0) %>% 
  group_by(subj) %>%
  summarize(n = n()) %>% 
  ungroup() %>% 
  summarize(`The unique values of the group wrong responses in catch trials` = unique(n)) %>% 
  kbl(format = "html", escape = F) %>%
  kable_styling(fixed_thead = T) %>% 
  kable_paper(full_width = F)
```


```{r eval=FALSE, include=FALSE}
data_full %>% 
  filter(is_practice == "True", group_correctness == 0) %>% 
  group_by(subj) %>%
  summarize(n = n()) %>% 
  ungroup() %>% 
  summarize(`The unique values of the group wrong responses in two practice blocks` = unique(n)) %>% 
  kbl(format = "html", escape = F) %>%
  kable_styling(fixed_thead = T) %>% 
  kable_paper(full_width = F)
```

```{r eval=FALSE, include=FALSE}

data_full %>%
  filter(is_catch == "True", group_correctness == 0) %>% 
  group_by(n_agents, block_num) %>% 
  summarise(n = n() / nrow(data_meta)) %>%
  ggplot(aes(n_agents, block_num, fill = n)) +
  geom_tile() +
  labs(title = "The number of repetitions for catch (group is wrong)",
       fill = "N repeat") +
  theme_bw()

```


# Plots
```{r}
p_load(hrbrthemes)

# print(nrow(data))

data <- data %>%
  filter(valid_subject, valid_trial)

# print(nrow(data))

```


```{r }

# eval=FALSE, include=FALSE
data %>%
  ggplot(aes(rt, group=id)) +
  geom_density() +
  scale_colour_ipsum() +
  theme_ipsum() +
  # xlim(c(0, 5.5 * 1000))
  labs(group = '')


```



```{r eval=FALSE, include=FALSE}
## RT overview
data %>%
  # filter(is_catch != "True", is_practice != "True") %>%
  filter(subject_response_time > 0.5, subject_response_time < 10) %>%
  ggplot(aes(x = trial_num, y = log(subject_response_time), color = congruency)) +
  geom_point(alpha = 0.6) +
  geom_abline(slope = 0, intercept = log(8), linetype = 2, alpha = 0.6) +
  geom_text(aes(y = log(8), label = "8s\n", x = 90), color = "black") +
  geom_abline(slope = 0, intercept = log(5), linetype = 2, alpha = 0.6) +
  geom_text(aes(y = log(5), label = "5s\n", x = 90), color = "black") +
  geom_abline(slope = 0, intercept = log(2), linetype = 2, alpha = 0.6) +
  geom_text(aes(y = log(2), label = "2s\n", x = 90), color = "black") +
  geom_vline(xintercept = 20, linetype = 4, alpha = 0.6, color = "black") +
  geom_vline(xintercept = 30, linetype = 4, alpha = 0.6, color = "black") +
  
  scale_colour_ipsum() + scale_fill_ipsum() +
  labs(x = "Trial number", y = "Log reaction time",
       color = "Flags positions") + 
  theme_ipsum()

```


```{r}

data %>%
  ggplot(aes(y = rt, x = n_agents, color = congruency)) +
  geom_smooth(method = "lm") +
  scale_colour_manual(values = c(rgb(0.2,0.7,0.1,0.5), rgb(0.7,0.2,0.1,0.5))) +
  facet_wrap(vars(group_alignment)) +
  theme_ipsum() +
  labs(x = "The number of agents", y = "Reaction time (s)",
       title = "Reaction time",
       fill = "Flags positions")


```

```{r}

data %>%
  mutate(group_alignment_rate = ifelse(group_alignment == "F", 1, 0)) %>% 
  ggplot(aes(color = congruency)) +
  geom_smooth(aes(y = group_alignment_rate, x = n_agents),
              method = "lm") +
  scale_colour_manual(values = c(rgb(0.2,0.7,0.1,0.5), rgb(0.7,0.2,0.1,0.5))) +
  geom_abline(slope = 0, intercept = 0.5) +
  theme_ipsum() +
  labs(x = "The number of agents", y = "Group alignment rate",
       title = "Conformity",
       color = "Flags positions")


```

```{r}

data %>%
  mutate(group_alignment_rate = ifelse(group_alignment == "F", 1, 0)) %>% 
  ggplot(aes(y = group_alignment_rate, x = first_agent_rt)) +
  geom_smooth(method = 'lm', label = "lm") +
  geom_abline(slope = 0, intercept = 0.5, linetype = 3, alpha = 1, color = 'red') +
  theme_ipsum() +
    labs(x = "The fastest agent reaction time", y = "Group alignment rate",
       title = "Conformity")


```

