---
title: "Analysis (Decision)"
author: "Valerii Chirkov"
date: '2022-09-16'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

```

```{r}
library("pacman")
p_load(tidyverse, brms, bayesplot, interactions, hrbrthemes, brmstools)

data <- readRDS(file = "data/data_filtered.rds")

head(data)

```



```{r}

# Set of slighlty informative priors
m1.priors <- c(
  prior(normal(0, 1), class = Intercept),
  prior(normal(0, 0.01), coef = "c_n_agents", class = b),
  prior(normal(0, 0.01), coef = "congruency1", class = b),
  prior(normal(0, 0.01), coef = "c_n_agents:congruency1", class = b),
  prior(normal(0, .1), class = sd),
  prior(lkj(2), class = cor)
)

m1.formula <- brmsformula(
  decision ~ 1 + c_n_agents * congruency + (1 + c_n_agents * congruency | subj))

m1.fit <- brm(
  formula = m1.formula,
  data = data,
  family = bernoulli(link = "logit"),
  prior = m1.priors,
  cores = 4,
  seed = 42)


```


```{r}

summary(m1.fit)

```

```{r}

round(fixef(m1.fit), 3)

```

```{r}

m1.df_fit <- as.data.frame(m1.fit) %>%
  dplyr::rename(
    n_agents = `b_c_n_agents`,
    intercept = `b_Intercept`,
    congruency = `b_congruency1`,
    `n_agents:congruency` = `b_c_n_agents:congruency1`
  )

mcmc_areas(
  m1.df_fit,
  pars = c("n_agents", "congruency", "n_agents:congruency"),
  prob = 0.8, # 80% intervals
  prob_outer = 0.99, # 99%
  point_est = "median"
) + ggplot2::labs(
  title = "Posterior parameter distributions",
  subtitle = "with medians and 80% intervals",
  
)

```

```{r}
data_summary <- data |>
  group_by(c_n_agents, congruency) |>
  summarise(mean = mean(decision),
            n = n(),
            se = sd(decision) / sqrt(n))
  

p <-interact_plot(m1.fit, pred = c_n_agents, modx = congruency, interval = TRUE)
  
p + 
  scale_colour_ipsum() +
  scale_fill_ipsum() +
  theme_ipsum() +
  labs(
    x = "The number of agens", 
    y = "Group allignment"
    ) 
# +
#   geom_point(data = data_summary, 
#              aes(y = mean, x = c_n_agents, color = congruency), 
#              inherit.aes = FALSE,
#              size = 3)
```


### Plot random effects

```{r}

m1.ranef <- data.frame(ranef(m1.fit))

```

```{r}

forest(m1.fit, grouping = "subj", pars = "Intercept", text = F, density = F)

```

```{r}

forest(m1.fit, grouping = "subj", pars = "congruency1", text = F, density = F)

```


### Plot correlations between random effects

```{r}

m1.ranef %>% 
  ggplot(aes(x = subj.Estimate.Intercept, y = subj.Estimate.c_n_agents)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
  title = "Correlation between random effects in the decision model",
  x = "Intercept adjustments",
  y = "The number of agents slope adjustments"
  
)

```

```{r}

m1.ranef %>% 
  ggplot(aes(x = subj.Estimate.c_n_agents, y = subj.Estimate.congruency1)) +
  geom_point() +
  geom_smooth(method = "lm")

```

```{r}

m1.ranef %>% 
  ggplot(aes(x = subj.Estimate.Intercept, y = subj.Estimate.congruency1)) +
  geom_point() +
  geom_smooth(method = "lm")

```


## Posterior Predictive Checks

### Posterior predictive checks for congruency x the number of agents

```{r}

ppc_bars_grouped(
  data$decision,
  yrep = posterior_predict(m1.fit, ndraws = 100),
  group = (data %>% dplyr::mutate(congruency_n_agents = paste0(congruency, "_", n_agents)))$congruency_n_agents
)

# dev.off()
```


### Posterior predictive checks for congruency x the number of agents

```{r}

#  ppc_bars_grouped(
#    (data %>% filter(subj %in% unique(subj)[1:10]))$decision,
#    yrep = posterior_predict(m1.fit, ndraws = 100),
#    group = (data %>% filter(subj %in% unique(subj)[1:10]))$subj
#  )

# dev.off()
```

### PSIS-LOO diagnostics 


```{r}
# Useful to check outlines (k > 0.7)
plot(loo(m1.fit))

```




## Session Information

```{r}
sessionInfo()
```

```{r}
devtools::session_info()
```
